server:
  port: 8082
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_DATABASE_USERNAME}
    url: jdbc:mysql://${RDS_DATABASE_URL}:${RDS_DATABASE_PORT}/${RDS_DATABASE_DB}
    password: ${RDS_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
